export const GOODS_SALES_THRESHOLD = 5
export const REFERENCE_DIFF_THRESHOLD = 15
export const STEAM_PURCHASE_THRESHOLD = 70
export const STEAM_CHECK_THRESHOLD = 55
export const BUFF_PURCHASE_THRESHOLD = 10

export const CURRENT_USER_ID = 'U1092757843'
