export const CURRENCY_MAPPING: Record<number, string> = {
  2001: 'USD',
  2002: 'GBP',
  2003: 'EUR',
  2004: 'CHF',
  2005: 'RUB',
  2006: 'PLN',
  2007: 'BRL',
  2008: 'JPY',
  2009: 'NOK',
  2010: 'IDR',
  2011: 'MYR',
  2012: 'PHP',
  2013: 'SGD',
  2014: 'THB',
  2015: 'VND',
  2016: 'KRW',
  2017: 'TRY',
  2018: 'UAH',
  2019: 'MXN',
  2020: 'CAD',
  2021: 'AUD',
  2022: 'NZD',
  2023: 'CNY',
  2024: 'INR',
  2025: 'CLP',
  2026: 'PEN',
  2027: 'COP',
  2028: 'ZAR',
  2029: 'HKD',
  2030: 'TWD',
  2031: 'SAR',
  2032: 'AED',
  2034: 'ARS',
  2035: 'ILS',
  2036: 'BYN',
  2037: 'KZT',
  2038: 'KWD',
  2039: 'QAR',
  2040: 'CRC',
  2041: 'UYU',
}

export const CURRENCY_DATA = {
  USD: {
    strCode: 'USD',
    eCurrencyCode: 1,
    strSymbol: '$',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: '',
  },
  GBP: {
    strCode: 'GBP',
    eCurrencyCode: 2,
    strSymbol: '£',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: '',
  },
  EUR: {
    strCode: 'EUR',
    eCurrencyCode: 3,
    strSymbol: '€',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: false,
    strDecimalSymbol: ',',
    strThousandsSeparator: ' ',
    strSymbolAndNumberSeparator: '',
  },
  CHF: {
    strCode: 'CHF',
    eCurrencyCode: 4,
    strSymbol: 'CHF',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ' ',
    strSymbolAndNumberSeparator: ' ',
  },
  RUB: {
    strCode: 'RUB',
    eCurrencyCode: 5,
    strSymbol: '₽',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: true,
    strDecimalSymbol: ',',
    strThousandsSeparator: '',
    strSymbolAndNumberSeparator: ' ',
  },
  BRL: {
    strCode: 'BRL',
    eCurrencyCode: 7,
    strSymbol: 'R$',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: ',',
    strThousandsSeparator: '.',
    strSymbolAndNumberSeparator: ' ',
  },
  JPY: {
    strCode: 'JPY',
    eCurrencyCode: 8,
    strSymbol: '¥',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: true,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  NOK: {
    strCode: 'NOK',
    eCurrencyCode: 9,
    strSymbol: 'kr',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: false,
    strDecimalSymbol: ',',
    strThousandsSeparator: '.',
    strSymbolAndNumberSeparator: ' ',
  },
  IDR: {
    strCode: 'IDR',
    eCurrencyCode: 10,
    strSymbol: 'Rp',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: true,
    strDecimalSymbol: '.',
    strThousandsSeparator: ' ',
    strSymbolAndNumberSeparator: ' ',
  },
  MYR: {
    strCode: 'MYR',
    eCurrencyCode: 11,
    strSymbol: 'RM',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: '',
  },
  PHP: {
    strCode: 'PHP',
    eCurrencyCode: 12,
    strSymbol: 'P',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: '',
  },
  SGD: {
    strCode: 'SGD',
    eCurrencyCode: 13,
    strSymbol: 'S$',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: '',
  },
  THB: {
    strCode: 'THB',
    eCurrencyCode: 14,
    strSymbol: '฿',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: '',
  },
  VND: {
    strCode: 'VND',
    eCurrencyCode: 15,
    strSymbol: '₫',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: true,
    strDecimalSymbol: ',',
    strThousandsSeparator: '.',
    strSymbolAndNumberSeparator: '',
  },
  KRW: {
    strCode: 'KRW',
    eCurrencyCode: 16,
    strSymbol: '₩',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: true,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  TRY: {
    strCode: 'TRY',
    eCurrencyCode: 17,
    strSymbol: 'TL',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: false,
    strDecimalSymbol: ',',
    strThousandsSeparator: '.',
    strSymbolAndNumberSeparator: ' ',
  },
  UAH: {
    strCode: 'UAH',
    eCurrencyCode: 18,
    strSymbol: '₴',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: true,
    strDecimalSymbol: ',',
    strThousandsSeparator: ' ',
    strSymbolAndNumberSeparator: '',
  },
  MXN: {
    strCode: 'MXN',
    eCurrencyCode: 19,
    strSymbol: 'Mex$',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  CAD: {
    strCode: 'CAD',
    eCurrencyCode: 20,
    strSymbol: 'CDN$',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  AUD: {
    strCode: 'AUD',
    eCurrencyCode: 21,
    strSymbol: 'A$',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  NZD: {
    strCode: 'NZD',
    eCurrencyCode: 22,
    strSymbol: 'NZ$',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  PLN: {
    strCode: 'PLN',
    eCurrencyCode: 6,
    strSymbol: 'zł',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: false,
    strDecimalSymbol: ',',
    strThousandsSeparator: ' ',
    strSymbolAndNumberSeparator: '',
  },
  CNY: {
    strCode: 'CNY',
    eCurrencyCode: 23,
    strSymbol: '¥',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: true,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  INR: {
    strCode: 'INR',
    eCurrencyCode: 24,
    strSymbol: '₹',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: true,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  CLP: {
    strCode: 'CLP',
    eCurrencyCode: 25,
    strSymbol: 'CLP$',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: true,
    strDecimalSymbol: ',',
    strThousandsSeparator: '.',
    strSymbolAndNumberSeparator: ' ',
  },
  PEN: {
    strCode: 'PEN',
    eCurrencyCode: 26,
    strSymbol: 'S/.',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: '',
  },
  COP: {
    strCode: 'COP',
    eCurrencyCode: 27,
    strSymbol: 'COL$',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: true,
    strDecimalSymbol: ',',
    strThousandsSeparator: '.',
    strSymbolAndNumberSeparator: ' ',
  },
  ZAR: {
    strCode: 'ZAR',
    eCurrencyCode: 28,
    strSymbol: 'R',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ' ',
    strSymbolAndNumberSeparator: ' ',
  },
  HKD: {
    strCode: 'HKD',
    eCurrencyCode: 29,
    strSymbol: 'HK$',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  TWD: {
    strCode: 'TWD',
    eCurrencyCode: 30,
    strSymbol: 'NT$',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: true,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  SAR: {
    strCode: 'SAR',
    eCurrencyCode: 31,
    strSymbol: 'SR',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  AED: {
    strCode: 'AED',
    eCurrencyCode: 32,
    strSymbol: 'AED',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  ARS: {
    strCode: 'ARS',
    eCurrencyCode: 34,
    strSymbol: 'ARS$',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: ',',
    strThousandsSeparator: '.',
    strSymbolAndNumberSeparator: ' ',
  },
  ILS: {
    strCode: 'ILS',
    eCurrencyCode: 35,
    strSymbol: '₪',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: '',
  },
  BYN: {
    strCode: 'BYN',
    eCurrencyCode: 36,
    strSymbol: 'Br',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: '',
  },
  KZT: {
    strCode: 'KZT',
    eCurrencyCode: 37,
    strSymbol: '₸',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: true,
    strDecimalSymbol: ',',
    strThousandsSeparator: ' ',
    strSymbolAndNumberSeparator: '',
  },
  KWD: {
    strCode: 'KWD',
    eCurrencyCode: 38,
    strSymbol: 'KD',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  QAR: {
    strCode: 'QAR',
    eCurrencyCode: 39,
    strSymbol: 'QR',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: false,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: ' ',
  },
  CRC: {
    strCode: 'CRC',
    eCurrencyCode: 40,
    strSymbol: '₡',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: true,
    strDecimalSymbol: ',',
    strThousandsSeparator: '.',
    strSymbolAndNumberSeparator: '',
  },
  UYU: {
    strCode: 'UYU',
    eCurrencyCode: 41,
    strSymbol: '$U',
    bSymbolIsPrefix: true,
    bWholeUnitsOnly: true,
    strDecimalSymbol: ',',
    strThousandsSeparator: '.',
    strSymbolAndNumberSeparator: '',
  },
  RMB: {
    strCode: 'RMB',
    eCurrencyCode: 9000,
    strSymbol: '刀币',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: true,
    strDecimalSymbol: '.',
    strThousandsSeparator: '',
    strSymbolAndNumberSeparator: ' ',
  },
  NXP: {
    strCode: 'NXP',
    eCurrencyCode: 9001,
    strSymbol: '원',
    bSymbolIsPrefix: false,
    bWholeUnitsOnly: true,
    strDecimalSymbol: '.',
    strThousandsSeparator: ',',
    strSymbolAndNumberSeparator: '',
  },
}
